[package]
name = "flac_description_generator"
version = "1.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
copypasta = "0.10.1"
lofty = "0.21.1"
log = "0.4.22"
regex = "1.11.1"
